### ISSUE TITLE
ISignalRGateway

### ISSUE THREAD

**Issue by jorbor** [amandiojribeiro/valantTest#1]
Why did you decide to create ISignalRGateway vs using directly IGateway?

**Comment by amandiojribeiro** [comment]
Hi Jordan,

IGateway is to generic (for me), but yes we could opt just to use directly IGateway.
However we can lose some isolation ISignalRGateway is typed and in this way we can organize things better, but this is the kind of thing we can discuss over a beer... 😎

Enviado do meu Windows Phone
________________________________
De: Jordan Hayashi<mailto:notifications@github.com>
Enviado: ‎21/‎03/‎2016 17:42
Para: amandiojribeiro/valantTest<mailto:valantTest@noreply.github.com>
Assunto: [valantTest] ISignalRGateway (#1)

Why did you decide to create ISignalRGateway vs using directly IGateway?

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/amandiojribeiro/valantTest/issues/1
