### ISSUE TITLE
ConcurrentQueue in GenericListRepository

### ISSUE THREAD

**Issue by drewburlingame** [amandiojribeiro/valantTest#2]
What prompted you to use a ConcurrentQueue instead of a ConcurrentDictionary?  What did the ConcurrentQueue give you and what are you missing by not using a ConcurrentDictionary?

**Comment by amandiojribeiro** [comment]
Simplicity, the Enqueue and TryDequeue methods are pretty straight forward.
I lost safety and performance on read (although you only se clear benefits on this in heavy use,then again it's what their made for). Safety because saving in "key value pair" is always safer, performance because you can get things in a faster way (key value pair again)...
